import socket
import threading
import time
import webview
from pathlib import Path
from http.server import HTTPServer, SimpleHTTPRequestHandler


"""
All the code concerning setuping and running the HTML server has been generated 
by AI. It is working as expected for instance.
The prompt to generate the code was: 
Run a simple HTTP server in a new thread to serve the files in the gui directory.
"""
GUI_DIR = Path(__file__).resolve().parent / "gui"
PORT = 8765
def run_server():
    handler = lambda *args, **kwargs: SimpleHTTPRequestHandler(
        *args, directory=str(GUI_DIR), **kwargs
    )
    try:
        server = HTTPServer(("", PORT), handler)
        server.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        server.serve_forever()
    except OSError as e:
        print(f"Erreur serveur (port {PORT} ?): {e}", flush=True)



def main():

    """
    As the setuping and running HTML server, the 3 lines bellow are also
    generated by AI. (same function)
    """
    server_thread = threading.Thread(target=run_server, daemon=True)
    server_thread.start()
    time.sleep(0.5)
    print("2. Serveur prêt, création fenêtre...", flush=True)

    webview.create_window(
        "Never be late",
        url=f"http://127.0.0.1:{PORT}/index.html",
        width=800,
        height=500,
        resizable=True,
    )
    webview.start(debug=False)


#For debugging, will be removed when main() will be call in another script.
if __name__ == "__main__":
    main()